FREEFORM_EXPLORATION_DECISION = "free_explore_decision"
HYPOTHESIZE_DECISION = "hypothesize_decision"
BUILD_INFERENCE_TREE_DECISION = "build_inference_tree_decision"
SYSTEM_QUERY_DECISION = "system_query_decision"
DONT_KNOW_DECISION = "dont_know_decision"
EXIT_DECISION = "exit_decision"
